//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADODECUENTA
    {
        public decimal IDMOVIMIENTO { get; set; }
        public Nullable<System.DateTime> FECHAMOVIMIENTO { get; set; }
        public string TIPOMOVIMIENTO { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal MONTO { get; set; }
        public Nullable<decimal> REFERENCIAID { get; set; }
        public Nullable<decimal> SALDOACUMULADO { get; set; }
    }
}
