//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVERSIONES
    {
        public int IDINVERSION { get; set; }
        public Nullable<int> IDCLIENTE { get; set; }
        public decimal MONTO { get; set; }
        public int PLAZOMESES { get; set; }
        public string TIPODEPAGO { get; set; }
        public System.DateTime FECHAINICIO { get; set; }
        public System.DateTime FECHAVENCIMIENTO { get; set; }
        public Nullable<decimal> INTERESESGANADOS { get; set; }
        public string ESTADO { get; set; }
    }
}
