//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROYECCIONPAGOS
    {
        public decimal IDPROYECCION { get; set; }
        public decimal IDPRESTAMO { get; set; }
        public byte NUMEROCUOTA { get; set; }
        public System.DateTime FECHAPAGO { get; set; }
        public decimal MONTOPAGO { get; set; }
        public string ESTADOPAGO { get; set; }
    
        public virtual PRESTAMOS PRESTAMOS { get; set; }
    }
}
