//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public decimal IDUSUARIO { get; set; }
        public string NOMBRECOMPLETO { get; set; }
        public string USUARIO { get; set; }
        public string CONTRASENA { get; set; }
    }
}
